---
- hosts: all
  user: root
  gather_facts: False
  pre_tasks:

  - name: installing apache2
    raw: apt-get -y install apache2


  - name: installing nginx
    raw: apt-get -y install nginx


  - name: installing php7.2
    raw: apt-get -y install php7.2
  - name: installing php7.2-fpm
    raw: apt-get -y install php7.2-fpm
  - name: installing php7.2-dev
    raw: apt-get -y install php7.2-dev
  - name: installing php7.2-curl
    raw: apt-get -y install php7.2-curl
  - name: installing php7.2-cli
    raw: apt-get -y install php7.2-cli
  - name: installing php7.2-mysql
    raw: apt-get -y install php7.2-mysql
  - name: installing php7.2-gd
    raw: apt-get -y install php7.2-gd
  - name: installing php7.2-xsl
    raw: apt-get -y install php7.2-xsl
  - name: restart php7.2
    raw: service php7.2-fpm restart

  - name: disable apache
    raw: service apache2 stop && service nginx start
  - name: restart your NGINX and PHP-PFM server
    raw: service nginx restart && service php7.2-fpm restart


  - name: installing mysql
    raw:  apt-get update && apt-get -y install mysql-server
 
 # Installing Magento
  - name: installing curl
    raw: apt-get -y install curl

  - name: installing composer
    raw: curl -sS https://getcomposer.org/installer | php

  - name: enable apache
    raw: a2enmod rewrite


  - name: changing directory
    raw: cd /var/www/html
  - name: download
    raw: wget https://github.com/magento/magento2/archive/2.0.0.zip
  - name: composer instalar
    raw: cd /var/www/html/ && composer install
