---
- hosts: all
  user: root
  gather_facts: False
  pre_tasks:

  - name: install all the required softwares
    apt:
       name:
         - php7.2
         - php7.2-mysql
         - php7.2-fpm
         - php7.2-dev
         - php7.2-curl
         - php7.2-cli
         - php7.2-gd
         - php7.2-xsl
         - apache2
         - nginx
         - mysql-server
         - curl
       state: present
       update_cache: true

  - name: restart php7.2
    raw: service php7.2-fpm restart

  - name: enable mod_proxy
    raw: a2enmod proxy_fcgi
  - name: new port
    raw: sed -i "s/listen =.*/listen = 127.0.0.1:9000/" /etc/php/7.2/fpm/pool.d/www.conf
  - name: php restart
    raw: service php7.2-fpm restart

  - name: disable apache
    raw: service apache2 stop && service nginx start
  - name: restart your NGINX and PHP-PFM server
    raw: service nginx restart && service php7.2-fpm restart


  - name: installing composer
    raw: curl -sS https://getcomposer.org/installer | php

  - name: enable apache
    raw: a2enmod rewrite

  - name: changing directory
    raw: cd /var/www/html
  - name: download
    raw: wget https://github.com/magento/magento2/archive/2.0.0.zip
  - name: composer instalar
    raw: cd /var/www/html/ && composer install
