---
- hosts: all
  user: root
  gather_facts: False
  pre_tasks:

  - name: installing apache2
    raw: apt-get -y install apache2


  - name: installing nginx
    raw: apt-get -y install nginx


  - name: installing php
    raw: apt-get -y install php


  - name: installing mysql
    raw: apt-get -y install mysql
